//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employe()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int RegistrationNumber { get; set; }
        public string Surname { get; set; }
        public string Name_ { get; set; }
        public string Patronymic { get; set; }
        public string Team { get; set; }
        public string Position { get; set; }
        public Nullable<bool> Free { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime DateStartWork { get; set; }
        public Nullable<System.DateTime> DateStopWork { get; set; }
        public string AdditionalDescription { get; set; }
        public long TelephoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}
